vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        cours_images:
           uri_prefix: /images/cours
           upload_destination: '%kernel.project_dir%/public/images/cours'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        cours_fond_images:
            uri_prefix: /images/cours/fond
            upload_destination: '%kernel.project_dir%/public/images/cours/fond'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        theme_images:
            uri_prefix: /images/donnee_seas/theme
            upload_destination: '%kernel.project_dir%/public/images/donnee_seas/theme'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        data_images:
            uri_prefix: /images/donnee_seas/data
            upload_destination: '%kernel.project_dir%/public/images/donnee_seas/data'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
